# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/camellia/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    dpm \
    gz \
    lk \
    mcupm \
    md1img \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee
